version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./settings:/app/settings
    command: python main.py

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: